# flake8: noqa
from .accounts import AccountTests
from .apiutils import ApiUtilsTests
from .client import ClientTests
from .collections import CollectionsTests
from .compatpatch import CompatPatchTests
from .discover import DiscoverTests
from .feed import FeedTests
from .friendships import FriendshipTests
from .highlights import HighlightsTests
from .igtv import IGTVTests
from .live import LiveTests
from .locations import LocationTests
from .media import MediaTests
from .misc import MiscTests
from .tags import TagsTests
from .upload import UploadTests
from .users import UsersTests
from .usertags import UsertagsTests
